import = ["/home/lilin/.config/alacritty/colors.toml"]
live_config_reload = true
#window.opacity = 1.0

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Underline"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "N"
mode = "~Search"
mods = "Control"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
startup_mode = "Windowed"
blur=true

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 18
y = 18
